base: "/rds/project/rs2099/rds-rs2099-toxgenomics/sita_gropro-seq"
homo_sapiens:
  bt_ribosomal: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/rrna/human"
  star: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/STAR"
  genes_gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/Homo_sapiens.GRCh38.102.gtf"
  blacklist_bed: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/hg38.blacklist1.bed"
mus_musculus:
  bt_ribosomal: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/rrna"
  star: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/STAR"
  genes_gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/Mus_musculus.GRCm38.102.gtf"
  blacklist_bed: ""
drosophila_melanogaster:
  bt_ribosomal: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/rrna"
  star: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/STAR"
  genes_gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/Drosophila_melanogaster.BDGP6.28.102.gtf"
  blacklist: ""
