base: "/rds/project/rs2099/rds-rs2099-toxgenomics/sita_gropro-seq"
homo_sapiens:
  bt_ribosomal: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/rrna/human"
  star: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/STAR"
  genes_gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/gencode.v34.annotation.gtf"
  blacklist_bed: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/hg38.blacklist1.bed"
  bedtools_genome: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/hg38.chrom.sizes"
mus_musculus:
  bt_ribosomal: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/rrna"
  star: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/STAR"
  genes_gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/gencode.vM25.annotation.gtf"
  blacklist_bed: ""
  bedtools_genome: ""
drosophila_melanogaster:
  bt_ribosomal: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/rrna"
  star: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/STAR"
  genes_gtf: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/drosophila/Drosophila_melanogaster.BDGP6.28.102.gtf"
  blacklist: ""
  bedtools_genome: ""
